// RefTracker 자막 프록시 서버
// 사용법: npm install 후 npm start
// RefTracker 설정 > 자막 프록시 URL 에 "이 서버 주소/transcript" 를 입력하세요.
// 예: https://your-app.onrender.com/transcript

const express = require('express');
const cors = require('cors');
const { YoutubeTranscript } = require('youtube-transcript');

const app = express();
const PORT = process.env.PORT || 3000;

// 모든 출처에서의 요청을 허용 (RefTracker가 브라우저에서 바로 호출하기 때문)
app.use(cors());

// 서버가 살아있는지 확인용
app.get('/', (req, res) => {
  res.json({ status: 'ok', message: 'RefTracker 자막 프록시 서버가 실행 중입니다.' });
});

// RefTracker가 실제로 호출하는 엔드포인트
// GET /transcript?videoId=VIDEO_ID
app.get('/transcript', async (req, res) => {
  const videoId = req.query.videoId;

  if (!videoId) {
    return res.status(400).json({ error: 'videoId 쿼리 파라미터가 필요합니다.' });
  }

  try {
    // 한국어 자막을 우선 시도하고, 없으면 자동 감지된 언어로 재시도
    let items;
    let usedLang = null;
    try {
      items = await YoutubeTranscript.fetchTranscript(videoId, { lang: 'ko' });
      usedLang = 'ko';
    } catch (e) {
      items = await YoutubeTranscript.fetchTranscript(videoId);
      usedLang = null;
    }

    if (!items || items.length === 0) {
      return res.status(404).json({ error: '이 영상에서 자막을 찾을 수 없습니다.' });
    }

    const segments = items.map(it => ({
      start: it.offset / 1000,
      duration: it.duration / 1000,
      text: it.text
    }));

    res.json({
      language: usedLang || (items[0] && items[0].lang) || 'unknown',
      isAutoGenerated: true, // youtube-transcript 라이브러리는 수동/자동 여부를 구분해 제공하지 않음
      segments
    });
  } catch (err) {
    console.error('[transcript proxy] error for videoId=' + videoId, err.message);
    if (/disabled/i.test(err.message)) {
      return res.status(404).json({ error: '이 영상은 자막이 비활성화되어 있습니다.' });
    }
    if (/not found|unavailable/i.test(err.message)) {
      return res.status(404).json({ error: '자막을 찾을 수 없거나 영상이 존재하지 않습니다.' });
    }
    res.status(500).json({ error: '자막을 가져오는 중 오류가 발생했습니다: ' + err.message });
  }
});

app.listen(PORT, () => {
  console.log(`RefTracker 자막 프록시 서버가 포트 ${PORT}에서 실행 중입니다.`);
  console.log(`로컬 테스트: http://localhost:${PORT}/transcript?videoId=dQw4w9WgXcQ`);
});
